# index
GET http://localhost:5000/api/comment

# show
###
GET http://localhost:5000/api/comment/180809

# update
###
PATCH  http://localhost:5000/api/comment/BSCS4A
Content-Type: application/json

{     
    "comment": "Good Teacher",
    "SID": "180809",
    "fid": "120956",
    "subject_id": "5",
    "class_id": "2",
    "sy_id": "1"
}

# insert
###
POST  http://localhost:5000/api/comment
Content-Type: application/json
 
{     
    "comment": "Good Teacher",
    "SID": "15088S",
    "fid": "120956",
    "subject_id": "5",
    "class_id": "2",
    "sy_id": "1"
}
