# index
GET http://localhost:5000/api/student

# show
###
GET http://localhost:5000/api/student/186969

# update
###
PATCH  http://localhost:5000/api/student/180493
Content-Type: application/json

{
  "username": "150884", 
  "password": "150884"
}

# delete
###
DELETE  http://localhost:5000/api/student/180999

# insert
###
POST  http://localhost:5000/api/student
Content-Type: application/json

{
  "SID": "186969",
  "Fname":"John Nico",
  "Lname": "Novero",
  "Age": "23",
  "Sex":"M",
  "Course": "BSIT",
  "class_id": "1",
  "username": "150884",
  "password":"150884"
}
