# index
GET http://localhost:5000/api/subject

# show
###
GET http://localhost:5000/api/subject/NC101

# update
###
PATCH  http://45.76.152.7:8080/api/subject/PHIL102
Content-Type: application/json

{   
    "code": "PHIL102",
    "subject": "Philosophy 102",
    "description": "Introduction to Philosophy"
}

###
PUT  http://localhost:5000/api/subject/PHIL102
Content-Type: application/json

{   
    "code": "PHIL102",
    "subject": "Philosophy 102",
    "description": "Introduction to Philosophy"
}

# delete
###
DELETE  http://localhost:5000/api/subject/NC101

# insert
###
POST  http://45.76.152.7:8080/api/subject
Content-Type: application/json
 
{   
    "code": "NC101",
    "subject": "Networks and Communication",
    "description": "Networks and Communication"
}
