# index
GET http://localhost:5000/api/school_year

# show
###
GET http://localhost:5000/api/school_year/2020-2021

# show_status
###
GET http://45.76.152.7:8080/api/school_year_status/Starting

# update
###
PUT  http://localhost:5000/api/school_year/2020-2021
Content-Type: application/json

{
    "year": "2020-2021",
    "semester": "1",
    "status": "Closed",
    "isActive": "Yes"
}

# delete
###
DELETE  http://localhost:5000/api/school_year/2020-2021

# insert
###
POST  http://localhost:5000/api/school_year
Content-Type: application/json

{
    "year": "2020-2021", 
    "semester": "1",
    "status": "Starting",
    "isActive": "Yes"
}

