# index
GET http://localhost:5000/api/user_logs

# show
###
GET http://localhost:5000/api/user_logs/Konics

# insert
###
POST  http://45.76.152.7:8080/api/user_logs
Content-Type: application/json

{
    "project_user": "Johnny Deff",
    "activity": "Login"
}